USE T_OPFLIX;

--DML
--INSERÇÃO

--TIPO USUÁRIO 
INSERT TIPOUSUARIO (TIPOUSUARIO) VALUES ('ADM');
INSERT TIPOUSUARIO (TIPOUSUARIO) VALUES ('CLIENTE');

SELECT * FROM TIPOUSUARIO;

--CATEGORIAS

INSERT CATEGORIA (CATEGORIA) VALUES ('ROMANCE');
INSERT CATEGORIA (CATEGORIA) VALUES ('TERROR');
INSERT CATEGORIA (CATEGORIA) VALUES ('FICÇÃO');
INSERT CATEGORIA (CATEGORIA) VALUES ('AVENTURA');
INSERT CATEGORIA (CATEGORIA) VALUES ('COMÉDIA');
INSERT CATEGORIA (CATEGORIA) VALUES ('ANIMAÇÃO');
INSERT CATEGORIA (CATEGORIA) VALUES ('DRAMA');
INSERT CATEGORIA (CATEGORIA) VALUES ('DOCUMENTÁRIO');
INSERT CATEGORIA (CATEGORIA) VALUES ('AÇÃO');

SELECT * FROM CATEGORIA ORDER BY IDCATEGORIA ASC;

--TIPO

INSERT TIPO (TIPO) VALUES ('FILME');
INSERT TIPO (TIPO) VALUES ('SERIE');

SELECT * FROM TIPO;

--PLATAFORMA

INSERT PLATAFORMA (PLATAFORMA) VALUES ('NETFLIX');
INSERT PLATAFORMA (PLATAFORMA) VALUES ('YOUTUBE');
INSERT PLATAFORMA (PLATAFORMA) VALUES ('CINEMA');
INSERT PLATAFORMA (PLATAFORMA) VALUES ('PRIME VIDEO');
INSERT PLATAFORMA (PLATAFORMA) VALUES ('VHS');

SELECT * FROM PLATAFORMA ORDER BY IDPLATAFORMA ASC;

--USUARIO



INSERT USUARIO (NOME, EMAIL, SENHA, TELEFONE, IDTIPOUSUARIO) VALUES ('HELENA', 'helen@email.com', '423456', '333', '1');
INSERT USUARIO (NOME, EMAIL, SENHA, TELEFONE, IDTIPOUSUARIO) VALUES ('ERIK', 'eri@email.com', '223457', '444', '2');
INSERT USUARIO (NOME, EMAIL, SENHA, TELEFONE, IDTIPOUSUARIO) VALUES ('ROBERTO', 'ro@email.com', '323458', '555', '1');
INSERT USUARIO (NOME, EMAIL, SENHA, TELEFONE, IDTIPOUSUARIO) VALUES ('CASSIANE', 'cassian@email.com', '3610', '777', '2');


SELECT * FROM USUARIO ORDER BY IDUSUARIO ASC;

DELETE USUARIO WHERE IDUSUARIO = 17;
DELETE USUARIO WHERE IDUSUARIO = 18;
DELETE USUARIO WHERE IDUSUARIO = 19;
DELETE USUARIO WHERE IDUSUARIO = 20;


--CLASSIFICACAO 
CREATE TABLE CLASSIFICACAO 
(
IDCLASSIFICACAO INT PRIMARY KEY IDENTITY 
,CLASSIFICACAO VARCHAR (200) NOT NULL
);

INSERT CLASSIFICACAO (CLASSIFICACAO) VALUES ('L');
INSERT CLASSIFICACAO (CLASSIFICACAO) VALUES ('10+');
INSERT CLASSIFICACAO (CLASSIFICACAO) VALUES ('12+');
INSERT CLASSIFICACAO (CLASSIFICACAO) VALUES ('16+');
INSERT CLASSIFICACAO (CLASSIFICACAO) VALUES ('18+');

SELECT * FROM CLASSIFICACAO ORDER BY IDCLASSIFICACAO;

--LANÇAMENTOS

INSERT LANCAMENTOS (TITULO, SINOPSE, IDCATEGORIA, IDTIPO, TEMPODURACAO, DATALANCAMENTO, IDPLATAFORMA, IDCLASSIFICACAO) VALUES ('Rei Leão', 'Traído e exilado de seu reino, o leãozinho Simba precisa descobrir como crescer e retomar seu destino como herdeiro real nas planícies da savana africana', '6', '1', '02:30', '18/06/2019', '3','1');
INSERT LANCAMENTOS (TITULO, SINOPSE, IDCATEGORIA, IDTIPO, TEMPODURACAO, DATALANCAMENTO, IDPLATAFORMA, IDCLASSIFICACAO) VALUES ('La casa de papel 3 temp', 'Um grupo de nove ladrões, liderados por um Professor, prepara o roubo do século na Casa da Moeda da Espanha, com o objetivo de fabricar o próprio dinheiro', '7', '2', '11:30', '10/06/2019', '1','4');
INSERT LANCAMENTOS (TITULO, SINOPSE, IDCATEGORIA, IDTIPO, TEMPODURACAO, DATALANCAMENTO, IDPLATAFORMA, IDCLASSIFICACAO) VALUES ('Toy Story 4', 'Woody, Buzz Lightyear e o resto da turma embarcam em uma viagem com Bonnie e um novo brinquedo chamado Forky.', '6', '1', '2:00', '20/06/2019', '3','1');
INSERT LANCAMENTOS (TITULO, SINOPSE, IDCATEGORIA, IDTIPO, TEMPODURACAO, DATALANCAMENTO, IDPLATAFORMA, IDCLASSIFICACAO) VALUES ('ANNABELE', 'FILME DE TERROR SOBRE UMA BONECA', '2', '1', '2:00', '18/06/19', '3','5');
INSERT LANCAMENTOS (TITULO, SINOPSE, IDCATEGORIA, IDTIPO, TEMPODURACAO, DATALANCAMENTO, IDPLATAFORMA, IDCLASSIFICACAO) VALUES ('TURMA DA MONICA', 'MONICA, MAGALI, CEBOLINHA E CASCÃO PARTEM EM AVENTURAS', '6', '1', '01:45', '18/09/2019', '3','1');
SELECT * FROM LANCAMENTOS ORDER BY IDLANCAMENTOS ASC;

DELETE LANCAMENTOS WHERE IDLANCAMENTOS = 6;
DELETE LANCAMENTOS WHERE IDLANCAMENTOS = 7;
DELETE LANCAMENTOS WHERE IDLANCAMENTOS = 8;

UPDATE USUARIO SET IDTIPOUSUARIO = '2' WHERE IDUSUARIO = 1;
UPDATE LANCAMENTOS SET TITULO = 'LA CASA DE PAPEL 3° TEMPORADA' WHERE IDLANCAMENTOS = 3;
UPDATE LANCAMENTOS SET DATALANCAMENTO = '08/07/1994' WHERE IDLANCAMENTOS = 1;
UPDATE LANCAMENTOS SET IDPLATAFORMA = 5 WHERE IDLANCAMENTOS = 1;
UPDATE USUARIO SET IMAGEM = 'https://3.bp.blogspot.com/--U3VZcvh954/WMloM41_fBI/AAAAAAAAJKs/PMTN6allydIWwWZTrFXf_5r_7UdqfO-cACLcB/s1600/checked_user1600.png' WHERE IDUSUARIO = 1;
UPDATE USUARIO SET IMAGEM = 'https://3.bp.blogspot.com/--U3VZcvh954/WMloM41_fBI/AAAAAAAAJKs/PMTN6allydIWwWZTrFXf_5r_7UdqfO-cACLcB/s1600/checked_user1600.png' WHERE IDUSUARIO = 6;
UPDATE USUARIO SET IMAGEM = 'https://3.bp.blogspot.com/--U3VZcvh954/WMloM41_fBI/AAAAAAAAJKs/PMTN6allydIWwWZTrFXf_5r_7UdqfO-cACLcB/s1600/checked_user1600.png' WHERE IDUSUARIO = 7;
UPDATE USUARIO SET IMAGEM = 'https://3.bp.blogspot.com/--U3VZcvh954/WMloM41_fBI/AAAAAAAAJKs/PMTN6allydIWwWZTrFXf_5r_7UdqfO-cACLcB/s1600/checked_user1600.png' WHERE IDUSUARIO = 4;

SELECT * FROM USUARIO ORDER BY IDUSUARIO ASC;
--NÃO VIEW
SELECT * FROM LANCAMENTOS WHERE IDCATEGORIA = 6;
SELECT TITULO, IDCATEGORIA FROM LANCAMENTOS WHERE IDCATEGORIA = 2;

ALTER TABLE USUARIO
ADD IMAGEM IMAGE;


/*CREATE VIEW CATEGS AS
SELECT TITULO, IDCATEGORIA FROM LANCAMENTOS
SELECT * FROM CATEGS WHERE IDCATEGORIA = 6; 

CREATE VIEW LANCS AS 
SELECT TITULO, IDCATEGORIA FROM LANCAMENTOS
SELECT * FROM LANCS WHERE IDCATEGORIA = 2; 

CREATE VIEW PLATS AS
SELECT TITULO, IDPLATAFORMA, IDCATEGORIA FROM LANCAMENTOS
SELECT * FROM PLATS;*/



