USE T_OPFLIX;

--DQL
--SELEÇÃO

SELECT * FROM TIPOUSUARIO;
SELECT * FROM CATEGORIA ORDER BY IDCATEGORIA ASC;
SELECT * FROM TIPO;
SELECT * FROM PLATAFORMA ORDER BY IDPLATAFORMA ASC;
SELECT * FROM USUARIO ORDER BY IDUSUARIO ASC;
SELECT * FROM CLASSIFICACAO ORDER BY IDCLASSIFICACAO;
SELECT * FROM LANCAMENTOS ORDER BY IDLANCAMENTOS ASC;

--QUANTIDADE DE USUÁRIOS

SELECT COUNT(NOME) AS CONTAGEUSUARIOS FROM USUARIO;

--DIFERENÇA DE DATA

select datediff(DAY, GETDATE(), '2019-09-13') AS QUANTOS_DIAS_FALTAM fROM LANCAMENTOS WHERE IDLANCAMENTOS = 1;
SELECT DATEDIFF(MONTH, GETDATE(), '2019-09-13') AS QUANTOS_MESES_FALTAM FROM LANCAMENTOS WHERE IDLANCAMENTOS = 1;

SELECT C.CATEGORIA
FROM CATEGORIA C ORDER BY IDCATEGORIA ASC;

SELECT U.NOME, U.IDTIPOUSUARIO
FROM USUARIO U ORDER BY IDUSUARIO ASC;

SELECT C.*,T.*
FROM CATEGORIA C, TIPO T;

SELECT L.IDLANCAMENTOS, C.IDCATEGORIA
FROM LANCAMENTOS L
RIGHT JOIN CATEGORIA C
ON L.IDLANCAMENTOS = C.IDCATEGORIA ORDER BY IDLANCAMENTOS ASC;

--N PODE USAR 2 TIPOS DE DADOS

SELECT L.IDLANCAMENTOS, P.IDPLATAFORMA
FROM LANCAMENTOS L
RIGHT JOIN PLATAFORMA P
ON L.IDLANCAMENTOS = P.IDPLATAFORMA ORDER BY IDLANCAMENTOS ASC;





